# This is a basic workflow to help you get started with Actions

name: Mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Remove unwanted files
        run: |
          echo Here we can cleanup stuff, but this action is now just a template
          echo on the main brancht, so it shows up in the actions tab.
      - name: Commit cleanup changes
        run: |
          git config --global user.email "${{ vars.MIRROR_EMAIL }}"
          git config --global user.name "${{ vars.MIRROR_USERNAME }}"
          git add .
          git commit -m "Mirror latest release"
      - name: Set destination to ${{ vars.MIRROR_REMOTE }}
        run: |
          git remote add mirror "https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/${{ vars.MIRROR_REMOTE }}.git"
          git fetch mirror
      - name: Mirror files locally to ${{ vars.MIRROR_REMOTE }}
        run: |
          git checkout -b forMirroring mirror/main
          git git rm -rf .
          git checkout main .
          git add .
          git commit -m "Mirror latest release"
          git push push mirror HEAD:main
