name: Test iOS implementation
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build klibs
        run: ./gradlew iosArm64MainKlibrary iosX64MainKlibrary
      - name: Run tests
        run: ./gradlew iosX64Test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: pupilidlib Tests
          path: pupilidlib/build/test-results/**/TEST*.xml
          reporter: java-junit
